### ISSUE TITLE
v2.0 boot-script can fail to load main.js in IE10

### ISSUE THREAD

**Issue by shogun70** [mobify/mobifyjs#139]
When I visit - for example - http://cdn.mobify.com/mobifyjs/examples/capturing-picturepolyfill/index.html in IE10, and then click in the address bar and press enter to reload the page, I get a blank page.

When I capture the network activity, the first visit loads all expected resources - including `mobify.js` and `main.js` - but on the second visit nothing is loaded after `mobify.js`. 

If I edit the boot-script so that `script.onload` is set **before** the script is inserted into the document then this issue is resolved. It seems that IE10 (and presumably IE9) has a subtle bug related to the the script preloading behavior.

**Comment by jansepar** [comment]
@shogun70 interesting! The strangest thing about this is that I cannot replicate this issue with using localhost examples - it only happens with the examples on the CDN. I tried fixing one of the examples doing what you suggested, and deployed it to the CDN and it solved the issue. Thanks a lot! I should have a pull request ready to fix most of the examples and an updated bootstrap tag tomorrow.

Also note, you mentioned IE9, but Mobify.js does not support IE9 at all because of its broken behaviour with `document.write`.

**Comment by shogun70** [comment]
@jansepar I presume the IE bug only occurs when the first script - in this case `mobify.js` - is loaded from browser cache. That may explain why the localhost examples don't fail.
